
jenkins_roles_list = [
  'misc',
  'oracle_java',
]


jenkins_shell_scripts_pre_chef = [
  {
    'inline': 'echo PRE_CHEF_TEST_SCRIPT'
  },
  {
    'path': '01_add_maven_repo_and_install_maven.sh' 
  }
]
jenkins_shell_scripts_post_chef = [
  {
    'inline': 'whoami;  id; pwd'
  },
  {
    'path': '02_build_and_install_or_update_tomcat.sh' 
  },
  {
    'path': '03_build_and_deploy_petclinic.sh'
  } 
]

########

gitlab_roles_list = [
  'gitlab'
]
gitlab_shell_scripts_pre_chef = []
gitlab_shell_scripts_post_chef = []

########


default_packages_to_install = [
  'mc', 
  'telnet',
  'traceroute',
  'git',
  'redhat-lsb-core', 
  'rpmdevtools'
]


nodes = {
  jenkins: {
    'instance_type': 'jenkins',
    box: 'centos/6',
    ip: '10.0.1.10',
    roles: jenkins_roles_list,
    'shell_scripts': [], 
  },
  gitlab: {
    instance_type: 'gitlab',
    box: 'centos/6',
    ip: '10.0.1.11',
    roles: gitlab_roles_list,
    'shell_scripts_pre_chef': gitlab_shell_scripts_pre_chef,
    'shell_scripts_post_chef': gitlab_shell_scripts_post_chef,
    'port_pairs': []
  }
}



app_config = {
  jenkins: {
    chef_json: {
      misc: {
        packages_to_install: default_packages_to_install,
      },
      jenkins: {
      }
    }
  },
  gitlab: {
    chef_json: {
      misc: {
        packages_to_install: default_packages_to_install,
      }
    }
  },
  apache: {
    chef_json: {
      frontend: {
        backends:[],
        apache_modules: [
          "expires",
          "deflate",
          "headers",
          "usertrack",
          "setenvif",
          "mime",
          "dav",
          "status",
          "autoindex",
          "info",
          "vhost_alias",
          "negotiation",
          "dir",
          "speling",
          "userdir",
          "alias",
          "substitute",
          "rewrite",
          "proxy",
          "proxy_balancer",
          "proxy_ftp",
          "proxy_http",
          "proxy_ajp",
          "proxy_connect",
          "cache",
          "suexec",
          "disk_cache",
          "cgi",
          "version"
       ]
     },
      misc: {
        packages_to_install: [
          'mc', 
          'telnet',
          'traceroute',
          'git'
        ]
      }
    }
  }
}

nodes.each do |nodename, nodedata|
  if nodedata[:instance_type] == 'backend'
    app_config[:apache][:chef_json][:frontend][:backends].push(nodedata[:ip])
  end
end


puts(app_config[:apache])

Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"

  nodes.each do |nodename, nodedata|
    puts(nodename)
    current_config = app_config[:"#{nodename}"]
    puts(current_config)
    config.vm.define nodename do |current_node|


      current_node.vm.network 'private_network', ip: nodedata[:ip]
      current_node.vm.provision :hosts, :sync_hosts => true

        
      if nodedata[:ports_pains].respond_to?('each')
        nodedata[:ports_pains].each do |port_pair| 
          current_node.vm.network "forwarded_port", guest: port_pair[:guest], host: port_pair[:host]
        end
      end      
              
      if nodedata[:shell_scripts_pre_chef].respond_to?('each')
        nodedata[:shell_scripts_pre_chef].each do |shell_script|
          puts(shell_script)
          shell_script.each do |method, script_code| 
            current_node.vm.provision "shell", "#{method}": script_code
          end
        end
      end
        
      current_node.vm.provision "chef_solo" do |chef|
        chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
        chef.roles_path = ["roles"]
          
        nodedata[:roles].each do |current_role|
          chef.add_role(current_role)
          chef.json = current_config[:chef_json]
        end    
      end

      if nodedata[:shell_scripts_post_chef].respond_to?('each')
        nodedata[:shell_scripts_post_chef].each do |shell_script|
          puts(shell_script)
          shell_script.each do |method, script_code| 
            current_node.vm.provision "shell", "#{method}": script_code
          end
        end
      end 
    end
  end
end
